package main.model.request;

public enum RequestType {
    COMM_CHANGE_NAME,
    COMM_CHANGE_DATES,
    COMM_CHANGE_CLOSING,
    COMM_CHANGE_USERGRP,
    COMM_CHANGE_LOCATION,
    COMM_CHANGE_TOTALSLOTS,
    COMM_CHANGE_CAMPCOMMSLOTS,
    COMM_CHANGE_DESCRIPTION,
}
